### ISSUE TITLE
will not genrate

### ISSUE THREAD

**Issue by leomidili988** [zurb/foundation-rails#262] opened 2018-05-03 23:46 UTC
`$ rails g foundation:install
Could not find generator 'foundation:install'. Maybe you meant 'integration_test', 'migration' or 't
est_unit:system'
Run `rails generate --help` for more options.
`

**Comment by ncoden** [comment] 2018-05-10 13:58
I @leomidili988.

Could you give more informations about your bug ? How are you using `foundation-rails`, how did you got this erros.

Thank you.

**Comment by ncoden** [comment] 2018-05-10 22:38
Duplicate of https://github.com/zurb/foundation-rails/issues/190

**Comment by ncoden** [comment] 2018-05-18 20:27
@leomidili988 It's not a problem. The thing is, in order to help you, we need to know what's wrong, so how you installed and used `foundation-rails` and how did you get into this problem.

I'm closing this for now as it seems this was an error on your side. However if you still got the error, feels free to reopen the issue and to provide all the informations you have: how you installed `foundation-rails`, what commands you run (and their logs), what are your `system`/`ruby`/`rails`/`foundation-rails` versions.

**Closed by ncoden** 2018-05-18 20:27 UTC
Labels: awaiting reply, duplicate
