### ISSUE TITLE
Fail to compile with sassc rails gem

### ISSUE THREAD

**Issue by anthony-robin** [zurb/foundation-rails#149] opened 2016-01-25 17:34 UTC
Hi, 
Not sure if this is related to sassc library or not but when I use foundation 6 gem into my rails project, I got this compiling error:
```
Error: media query expression must begin with '('
on line 138 of .rvm/gems/ruby-2.2.2/gems/foundation-rails 6.1.1.3/vendor/assets/scss/util/_breakpoint.scss
```

**Comment by arthurzurb** [comment] 2016-01-25 19:02
Hey @anthony-robin,

I am not familiar with sassc with the foundation gem, we use sass-rails here. Did you run into this issue when installing Foundation in your project, or did this show when updating the gem?

**Comment by anthony-robin** [comment] 2016-01-25 19:11
I recently switch from **sass-rails** to **sassc-rails** because the compiling time was very very slow with the first solution.  
After switching to **sassc-rails** I didn't have any compiling error with Foundation 5 but after updating to Foundation 6 the error append.  

To recap:
``` shell
- sass-rails + Foundation 5 # Work
- sass-rails + Foundation 6 # I haven't tried, I switched to sassc-rails before
- sassc-rails + Foundation 5 # Work
- sassc-rails + Foundation 6 # Compiling error
```

I also submitted the issue to sassc-rails repository.
Thanks !

**Comment by mehlah** [comment] 2016-01-27 04:26
>  I made other tests and it appears that sassc is the guilty one

@anthony-robin do you mean you found the reason why it broke?
I can't reproduce it on my machine.

**Comment by anthony-robin** [comment] 2016-01-27 08:38
No, I have no idea why it's not working with sassc.
When I tried to compile Foundation 6 with sass it works so I concluded that sassc is the reason of the error.

**Comment by darcy** [comment] 2016-01-27 18:26
I have the same issue here with 6.1.2. Also, trying to switch to sassc-rails from sass-rails which worked fine. Same reason for the switch: long compile times. sassc uses libsass under the hood which I think is what is complaining about this?

```
ActionView::Template::Error (Error: media query expression must begin with '('
        on line 139 of ../../local/bundle/gems/foundation-rails-6.1.2.0/vendor/assets/scss/util/_breakpoint.scss
>> 
   -----------^
```

Here are some versions:
```
rails 4.2.5
sassc-rails 1.2.0
sassc 1.8.4
libsass 3.3.3
foundation-rails 6.1.2.0
```
@mehlah you mentioned you can't reproduce, what version of sassc-rails did you try?

**Comment by decabeza** [comment] 2016-02-05 11:16
Hi, same error. I´m changed "gem 'sassc-rails'" in my Gemfile to:

**gem 'sass-rails', '~> 5.0', '>= 5.0.4'**

And the error disappear :wink:

**Comment by mikemerritt** [comment] 2016-02-18 00:05
This mis an issue with libsass 3.3.3. Please refer to this issue for a temporary workaround. https://github.com/sass/sassc-rails/issues/57

**Comment by mikemerritt** [comment] 2016-04-13 02:34
This is now fixed in the latest version of sassc and therefore sassc-rails.

**Closed** 2016-07-21 07:50 UTC
